### ISSUE TITLE
COBYLA: increase RHO

### ISSUE THREAD

**Issue by FrancoisGallard** [pdfo/pdfo#4]
Hi,

We need to improve the performance of COBYLA when the TR was reduced too much. This kind of improvement has been added in the NLOPT distribution of COBYLA.

I have made a dirty modification here https://github.com/FrancoisGallard/pdfo/tree/ft_increase_tr
cobylb.f, Line 764:
```
C Increase TR
      IF (TRURED > 0.0D0 .AND. TRURED >= 0.9D0*PREREM)
            RHO=2*RHO
      END IF
```
This seems to work in our environment and provides big gains in some situations (4x faster on our test case).

However we have our own stopping criteria (xtol, ftol) outside COBYLA and I think this modification breaks the stopping criteria in COBYLA.
Maybe it would be required to add such criteria in this implementation of COBYLA in case this option is active.

What do you think?

Best,
François

**Comment by pdfo** [comment]
Salut François,

I agree that increasing the trust-region radius is a good idea. Indeed, Powell introduced a strategy to increase the radius in all the other derivative-free solvers of his (UOBYQA, NEWUOA, BOBYQA, and LINCOA). I believe that he would have done the same in COBYLA if he had implemented COBYLA later. 

I am very happy to know that the simple change you made can lead to significant gains. However, for the moment, on our side, we will keep Powell's code "as is". 

Indeed, we are working on a re-implementation of Powell's solvers in modern languages --- first Fortran 2003, and the MATLAB, Python, and others. It will be a ***totally faithful*** re-implementation. The new code will be ***equivalent*** to Powell's, not only mathematically but also numerically. In other words, the new code will not change Powell's algorithms at all, and it will produce ***exactly the sam***e results as Powells. The focus is to re-implement Powell's solvers in a modulized and structured way so that they are readable, maintainable, and extendable. The new code will be no GOTO (of course), and will use matrix-vector procedures instead of loops whenever it is possible. 

Before finishing the re-implemetation, I refrain from making any change to Powell's code on my side. Due to the unique coding style, Powell's code has extremely high complexity --- I would say that nobody can see the true complexity before trying to disentangle the GOTOs, which I am currently working on. Consequently, changing one place will inevitably affect many other places (e.g., the stopping criteria you mentioned), sometimes in a way that is hard to imagine, as I am encountering every day during the re-implementation. Making changes to such code is like introducing new wires in a machine that has already excessively many wires, buttons, knobs, and switches. It may do some good, but I guess it is better to postpone the changes until the machine is modulized and the structure becomes clearer. 

The re-implementation is not trivial due to the complexities mentioned before. Recall that we want to have a totally faithful reimplementation. Hence intensive tests are needed for ***almost every line of code***, which is quite time-consuming. I have finished the  Fortran 2003  version of  NEWUOA, and currently working on COBYLA. It has taken me two summers. I hope to finish it before the end of next summer. I will let you know when it is ready.

Many thanks for your interest and attention. We hope our work is helpful to you and to others. 

Best regards,
Zaikun

**Comment by FrancoisGallard** [comment]
Hello Zaikun,

Thanks for your clear reply.

I fully understand your position, and I agree that doing this code refactoring is the only way to keep this code alive, getting rid of the GOTOs would be awesome. It's perfect if you can write tests too. I wish you good luck in this hard and important work. Yes, I can confirm your work is very helpful.

We really need this improvement, so I think we are going to make some comparisons on a set of Cutest problems with the modification and without, to validate it and maybe improve it. If you already have some advices on how to make this better than what I did, I would be happy to read them.

Best Regards

François

**Comment by pdfo** [comment]
Salut, François !

Sorry for the slow reply --- I have been immersed in the reimplemented COBYLA in the past week.

Thank you for your nice words. Given the amount of time and effort that Tom and I have spent on this project, it is reassuring and encouraging to hear practitioners like you confirm the usefulness of our work. This kind of feedback is important for us to continue. 

I totally see the necessity of making the proposed changes in your applications. I speculate that allowing RHO to increase would improve the performance of COBYLA on a considerable class of problems, including some from CUTEst. We will be very interested to hear about the result of your comparison. 

On our side, we will surely consider increasing RHO and respecting bounds after we get the modernized version of COBYLA. We will let you know at that time, but it may not happen very soon. 

BTW, I personally would not use "refactoring" to describe the work of modernizing Professor Powell's code. It is much more than that. I sometimes compare it with the job of translating/interpreting/annotating a classical work like Euclid's *Elements*. Doing this job, I wish to keep Powell's solvers understandable and accessible to everyone, not only the experts; or, as you said, keep them alive. Very few people remember who translated *Elements*, but it is a job that must be done. I see it as my mission since Professor Powell asked me to maintain his code in his last days and I promised him that I would commit myself to the maintenance. In addition, I know Powell's algorithms and code very well. 

Thanks again for your attention and feedback. 

Bon week-end !

Zaikun

**Comment by zaikunzhang** [comment]
Hi Francois @FrancoisGallard ,

The promised modernized implementation of Powell's methods is available now: 

www.libprima.net

It does not only modernize the code (removing all GOTOs, of course), but also fixes a lot of bugs, and introduces considerable improvements (more to come). Therefore, it is named after PRIMA, where "P" stands for "Powell", while "RIMA" is an acronym for "Reference Implementation with Modernization and Amelioration". 

It took me almost three years of full-gear coding. I hope I am the last person in the world who ever need to work on Powell's original Fortran 77 code.   

For more information, check the address above. Thanks for your attention. 

A+,
Zaikun

**Comment by FrancoisGallard** [comment]
Hello Zaikun,

Congratulations for such awesome work ! The data profiles are very impressive.

Is there any Python interface ? Do you plan to update pdfo with this implementation?

François

**Comment by zaikunzhang** [comment]
Hi @FrancoisGallard ,

>  which in turn calls `fmxCallMATLAB`, a subroutine provided by MATLAB to evaluate `fun_ptr`. 

This pull request provides a Python interface of PRIMA that seems to work, at least for double precision:

https://github.com/libprima/prima/pull/28

You may try it if you are interested. However, please do note that **it is by me, and it is not part of PRIMA yet. ** 

**PDFO will likely stay unchanged. It will continue to use the Fortran 77 code, and no updates will be made to the Fortran 77 code anymore. ** PRIMA is a different project. 

Merci !

Zaikun

**Comment by FrancoisGallard** [comment]
Hi @zaikunzhang : That is really nice !

So if I understand, you are going to integrate this pull request in Prima?
Maybe I will wait for the merge request to be integrated and for sure we will try it.
Thanks to you !

I also see that there are good ongoing discussions to have a scipy interface which is the best option in my opinion. That would be perfect from a maintenance point of view.

Best,
François

**Comment by zaikunzhang** [comment]
Hi @FrancoisGallard 

> So if I understand, you are going to integrate this pull request in Prima?

Yes, as long as the problems in this pull request are solved. 

> I also see that there are good ongoing discussions to have a scipy interface which is the best option in my opinion. That would be perfect from a maintenance point of view.

I  hope very much that PRIMA (or part of it) will be included into SciPy. But this needs a lot of work. 

Best regards,
Zaikun

**Comment by FrancoisGallard** [comment]
Hi @zaikunzhang : ok thanks so we wil go first for the direct Prima python interface.

Best,
Francois
